[package]
name = "build_a_pile_of_cubes"
version = "0.1.0"
authors = ["Colin Fendrick <colin.fendrick@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
